=== apache/geode/geode-client-native/src/tests/xml/testDefinition.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:include schemaLocation="gfcpp-cache.xsd" />
  <xs:element name="test-driver" type="Test-Driver">
    <xs:annotation>
      <xs:documentation>The container for all the information required to perform a test. This is
        the root level element.</xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:complexType name="Test-Driver">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="localFile" type="Local-File" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="data" type="Data" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="data-set" type="Data-Set" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="client-set" type="Client-Set" minOccurs="0" />
      <xs:element name="test" type="Test" minOccurs="0" maxOccurs="unbounded" />
    </xs:choice>
    <xs:attribute name="version" type="xs:string" use="optional" />
  </xs:complexType>
  <xs:complexType name="Test">
    <xs:annotation>
      <xs:documentation>A collection of tasks that comprise a single test.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="task" type="Task" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Printed in some log messages.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="description" type="xs:string" use="optional">
      <xs:annotation>
        <xs:documentation>Not logged currently.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="waitTime" type="xs:string" use="optional">
      <xs:annotation>
        <xs:documentation>Not recommended for use, will cause test to fail if it has not completed
          in this number of seconds.</xs:documentation>
        <xs:documentation>Use the waitTime associated with tasks instead.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="timesToRun" type="xs:int" use="optional">
      <xs:annotation>
        <xs:documentation>Total number of times to run this task. If any executions of the task
          return an error status, further execution of the task will continue, only if
          continueOnError is set to true.</xs:documentation>
        <xs:documentation>timesToRun defaults to once per client, specifying "1" would run it once
          on one client.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  <xs:complexType name="Task">
    <xs:annotation>
      <xs:documentation>A single task, currently a function within a library, for
      execution.</xs:documentation>
    </xs:annotation>
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="data" type="Data" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="client-set" type="Client-Set" minOccurs="0" />
    </xs:choice>
    <xs:attribute name="name" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Name of the task, used in some log messages.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="action" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>The name of the extern "C" function that will be looked up in the library
          and executed.</xs:documentation>
        <xs:documentation>The reason for calling it an action is to not marry too tightly the notion
          that this is only a function, in the future it should be possible to extend support to
          different flavors of clients.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="class" type="xs:string" use="optional">
      <xs:annotation>
        <xs:documentation>The name of the class to load, when using assemblies.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="container" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>The name of the library to load.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="waitTime" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>The number of seconds to wait for task to complete before assuming client
          is hung and killing it.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="timesToRun" type="xs:int" use="optional">
      <xs:annotation>
        <xs:documentation>Total number of times to run this task. If any executions of the task
          return an error status, further execution of the task will continue, only if
          continueOnError is set to true.</xs:documentation>
        <xs:documentation>timesToRun defaults to once per client, specifying "1" would run it once
          on one client.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="threadCount" type="xs:int" use="optional">
      <xs:annotation>
        <xs:documentation>Number of threads each client should run this task on.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="parallel" type="xs:boolean" use="optional">
      <xs:annotation>
        <xs:documentation>Run this task in parallel with the previous task.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="continueOnError" type="xs:boolean" use="optional">
      <xs:annotation>
        <xs:documentation>When running this task multiple times, continue to schedule it on clients,
          even if any results returned have been failures.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  <xs:complexType name="Local-File">
    <xs:annotation>
      <xs:documentation>Specify content for a file, may optionally specify whether to append to
        existing file, default is to append.</xs:documentation>
    </xs:annotation>
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="append" type="xs:boolean" use="optional" default="false" />
        <xs:attribute name="description" type="xs:string" use="optional" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="Client-Set">
    <xs:annotation>
      <xs:documentation>A collection of client elements.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="client" type="Client" maxOccurs="unbounded" minOccurs="0" />
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="optional" />
    <xs:attribute name="exclude" type="xs:boolean" use="optional" />
    <xs:attribute name="count" type="xs:int" use="optional" />
    <xs:attribute name="begin" type="xs:int" use="optional" />
    <xs:attribute name="hostGroup" type="xs:string" use="optional" />
    <xs:attribute name="remaining" type="xs:boolean" use="optional" />
  </xs:complexType>
  <xs:complexType name="Client">
    <xs:annotation>
      <xs:documentation>A single client, used when it is necessary to restrain what clients will be
        used for a particular task.</xs:documentation>
      <xs:documentation>Also useful for specifying a minimum number of clients for the test,
        regardless of how few hosts are provided on the commandline.</xs:documentation>
    </xs:annotation>
    <xs:attribute name="name" type="xs:string" use="required" />
    <xs:attribute name="program" type="xs:string" use="optional" />
    <xs:attribute name="arguments" type="xs:string" use="optional" />
  </xs:complexType>
  <xs:complexType name="Data-Set">
    <xs:annotation>
      <xs:documentation>A collection of data elements.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="data" type="Data" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="optional" />
  </xs:complexType>
  <xs:complexType name="Data" mixed="true">
    <xs:annotation>
      <xs:documentation>Data item that can be accessed by name from the application at
      runtime.</xs:documentation>
    </xs:annotation>
    <xs:choice minOccurs="0" maxOccurs="1">
      <xs:element name="list" type="List" />
      <xs:element name="oneof" type="Oneof" />
      <xs:element name="range" type="Range" />
      <xs:element name="snippet" type="Snippet" />
    </xs:choice>
    <xs:attribute name="name" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>The name to be used in the application to find the value associated with
          this data element.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  <xs:complexType name="List">
    <xs:annotation>
      <xs:documentation>A list of items that can be accessed from the application using first, next
        semantics.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="item" type="xs:string" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="Oneof">
    <xs:annotation>
      <xs:documentation>A data item that randomly returns one of the items it contains each time
        getValue is called on it.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="item" type="xs:string" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="Range">
    <xs:annotation>
      <xs:documentation>A random number between its low and high attribute values will be returned
        each time its getValue function is called.</xs:documentation>
    </xs:annotation>
    <xs:attribute name="low" type="xs:double" use="required">
      <xs:annotation>
        <xs:documentation>Low end of range used in selecting a random number.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="high" type="xs:double" use="required">
      <xs:annotation>
        <xs:documentation>High end of range used in selecting a random number.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  <xs:complexType name="Snippet">
    <xs:annotation>
      <xs:documentation>A root-region element as would be suitable for a cache.xml
      file.</xs:documentation>
    </xs:annotation>
    <xs:choice>
      <xs:element name="region" type="Region" />
      <xs:element name="pool" type="Pool" />
    </xs:choice>
  </xs:complexType>
</xs:schema>

=== apache/geode/geode-client-native/src/tests/xml/NativePR/perfTestPutGetDestroyTCRscaledUp.xml
<?xml version="1.0" encoding="UTF-8"?>
<test-driver version="1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../testDefinition.xsd">

  <data name="timedInterval">60</data>
  <data name="cacheType">CLIENT</data>
  <data name="keySize">
    <list>
      <item>16</item>
      <!--item>32</item>
      <item>64</item>
      <item>128</item>
      <item>256</item-->
    <!--range low="10" high="256"/-->
    </list>
  </data>
  

  <data name="distinctKeys">
    <list>
      <item>10</item>
      <item>1000</item>
      <item>10000</item>
      <!--item>100000</item>
      <item>184877</item-->
    </list>
  </data>
	
  <data name="valueSizes">
    <list>
      <item>100</item>
      <item>1000</item>
      <item>10000</item>
             <!--item>5000</item>
             <item>10000</item-->
    </list>
  </data>
	
  <data name="numThreads">
    <list>
      <item>10</item>
    </list>
  </data>

  <data name="keyType">str</data>

  <data name="ThinClientRegion">
    <snippet>
      <region name="TestTCR1">
        <region-attributes caching-enabled="true" client-notification="true"/>
      </region>
    </snippet>
  </data>
  <data name="regionSpec">ThinClientRegion</data>

  <client-set name="JCS1" hostGroup="CS"/>
  <client-set name="JCS2" hostGroup="CS"/>
  <client-set name="JCS3" hostGroup="CS"/>
  <client-set name="Putter1"/>
  <client-set name="Getter1"/>
  <client-set name="Destroyer1"/>
  <client-set name="Putter2"/>
  <client-set name="Getter2"/>
  <client-set name="Destroyer2"/>
  <client-set name="Putter3"/>
  <client-set name="Getter3"/>
  <client-set name="Destroyer3"/>
  <client-set name="Putter4"/>
  <client-set name="Getter4"/>
  <client-set name="Destroyer4"/>
	
  <test name="ThinClientPerf" description="Thin Client perf test">
    <task name="SetupCacheServer" action="doRunProcess" container="utils" waitTime="5m">
      <data name="program">setupJavaServers</data>
      <data name="arguments">-c 3 NativePR/csNotifySubscription.xml</data>
      <client-set name="JCS1"/>
    </task>
    <task name="StartCacheServer 1" action="doRunProcess" container="utils" waitTime="10m" parallel="true">
      <data name="program">startJavaServers</data>
      <data name="arguments">1</data>
      <client-set name="JCS1"/>
    </task>
    <task name="StartCacheServer 2" action="doRunProcess" container="utils" waitTime="10m" parallel="true">
      <data name="program">startJavaServers</data>
      <data name="arguments">2</data>
      <client-set name="JCS2"/>
    </task>
    <task name="StartCacheServer 3" action="doRunProcess" container="utils" waitTime="10m" parallel="true">
      <data name="program">startJavaServers</data>
      <data name="arguments">3</data>
      <client-set name="JCS3"/>
    </task>
     <task name="CreateRegion" action="doCreateRegion" container="perftests" waitTime="5m">
      <client-set name="Putter1"/>
      <client-set name="Getter1"/>
      <client-set name="Destroyer1"/>
    </task>
    <task name="Register All Keys" action="doRegisterAllKeys" container="perftests" waitTime="2m">
      <client-set name="Putter1"/>
      <client-set name="Getter1"/>
      <client-set name="Destroyer1"/>
    </task>
    <task name="Measure Put Throughput" action="doPuts" container="perftests" waitTime="30m">
      <client-set name="Putter1"/>
    </task>
    <task name="Measure Get Throughput" action="doGets" container="perftests" waitTime="30m">
      <client-set name="Getter1"/>
    </task>
    <task name="Measure Destroy Throughput" action="doGets" container="perftests" waitTime="30m">
      <client-set name="Destroyer1"/>
    </task>
	
    <task name="CreateRegion" action="doCreateRegion" container="perftests" waitTime="5m">
      <client-set name="Putter2"/>
      <client-set name="Getter2"/>
      <client-set name="Destroyer2"/>
    </task>
    <task name="Register All Keys" action="doRegisterAllKeys" container="perftests" waitTime="2m">
      <client-set name="Putter2"/>
      <client-set name="Getter2"/>
      <client-set name="Destroyer2"/>
    </task>
    <task name="Measure Put Throughput" action="doPuts" container="perftests" waitTime="30m">
      <client-set name="Putter2"/>
    </task>
    <task name="Measure Get Throughput" action="doGets" container="perftests" waitTime="30m">
      <client-set name="Getter2"/>
    </task>
    <task name="Measure Destroy Throughput" action="doGets" container="perftests" waitTime="30m">
      <client-set name="Destroyer2"/>
    </task>
	   <!-- create region and measure throughput for putter,getter,destroyer - 3 -->
	
    <task name="CreateRegion" action="doCreateRegion" container="perftests" waitTime="5m">
      <client-set name="Putter3"/>
      <client-set name="Getter3"/>
      <client-set name="Destroyer3"/>
    </task>
    <task name="Register All Keys" action="doRegisterAllKeys" container="perftests" waitTime="2m">
      <client-set name="Putter3"/>
      <client-set name="Getter3"/>
      <client-set name="Destroyer3"/>
    </task>
    <task name="Measure Put Throughput" action="doPuts" container="perftests" waitTime="30m">
      <client-set name="Putter3"/>
    </task>
    <task name="Measure Get Throughput" action="doGets" container="perftests" waitTime="30m">
      <client-set name="Getter3"/>
    </task>
    <task name="Measure Destroy Throughput" action="doGets" container="perftests" waitTime="30m">
      <client-set name="Destroyer3"/>
    </task>
	   <!-- create region and measure throughput for putter,getter,destroyer - 4 -->
	
    <task name="CreateRegion" action="doCreateRegion" container="perftests" waitTime="5m">
      <client-set name="Putter4"/>
      <client-set name="Getter4"/>
      <client-set name="Destroyer4"/>
    </task>
    <task name="Register All Keys" action="doRegisterAllKeys" container="perftests" waitTime="2m">
      <client-set name="Putter4"/>
      <client-set name="Getter4"/>
      <client-set name="Destroyer4"/>
    </task>
    <task name="Measure Put Throughput" action="doPuts" container="perftests" waitTime="30m">
      <client-set name="Putter4"/>
    </task>
    <task name="Measure Get Throughput" action="doGets" container="perftests" waitTime="30m">
      <client-set name="Getter4"/>
    </task>
    <task name="Measure Destroy Throughput" action="doGets" container="perftests" waitTime="30m">
      <client-set name="Destroyer4"/>
    </task>
	   <!-- stopping all the 4 servers -->

    <task name="Close Cache" action="doCloseCache" container="perftests" waitTime="2m"/>
    <task name="StopCacheServer 1" action="doRunProcess" container="utils" waitTime="10m" parallel="true">
      <data name="program">stopJavaServers</data>
      <data name="arguments">1</data>
      <client-set name="JCS1"/>
    </task>
    <task name="StopCacheServer 2" action="doRunProcess" container="utils" waitTime="10m" parallel="true">
      <data name="program">stopJavaServers</data>
      <data name="arguments">2</data>
      <client-set name="JCS2"/>
    </task>
    <task name="StopCacheServer 3" action="doRunProcess" container="utils" waitTime="10m" parallel="true">
      <data name="program">stopJavaServers</data>
      <data name="arguments">3</data>
      <client-set name="JCS3"/>
    </task>
</test-driver>

=== apache/geode/geode-client-native/src/tests/xml/Generics/parReg/pdx/Pdx/pdxPutGetMerge.xml
<?xml version="1.0" encoding="UTF-8"?>
<test-driver version="1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../testDefinition.xsd">

  <data name="timedInterval">60</data>
  <data name="cacheType">CLIENT</data>

  <data name="distinctKeys">
    <list>
      <item>100</item>
    </list>
  </data>

  <data name="valueSizes">
    <list>
      <item>10</item>
    </list>
  </data>
  <data name="numThreads">
    <list>
      <item>4</item>
    </list>
  </data>
  <data name="keyType">str</data>
  <data name="clientCount">4</data>
  <data name="serialExecution">true</data>
  <data name="objectType">PdxVersioned</data>
  
  <data name="ThinClientPool1">
    <snippet>
      <pool name="_Test_Pool1" subscription-enabled="true" thread-local-connections="false" min-connections="2" read-timeout="3600000" 
           subscription-redundancy="0" load-conditioning-interval="5000" servers="true" />
    </snippet>
  </data>
  <data name="ThinClientRegion">
    <snippet>
      <region name="TestTCR1">
        <region-attributes caching-enabled="true" pool-name="_Test_Pool1">
        </region-attributes>
      </region>
    </snippet>
  </data>
<data name="EmptyClientRegion">
  <snippet>
    <region name="TestTCR1">
      <region-attributes caching-enabled="false" pool-name="_Test_Pool1">
      </region-attributes>
    </region>
  </snippet>
</data>
                                 

  <client-set name="JCS1" hostGroup="CS"/>
  <client-set name="JCS2" hostGroup="CS"/>
  <client-set name="JCS3" hostGroup="CS"/>
  <client-set count="4" name="Client"/>

  <test name="pdxPutGetMerge" description="This test executes operations on entries on a PartitionedRegion and carefully
validates for correctness. The data store for the partitioned region is spread
across all VMs. The test put one version of pdx class from few clients and get from other clients.">
    <task name="SetupCacheServer CS1" action="doRunProcess" container="utils" waitTime="5m">
      <data name="program">setupJavaServers</data>
      <data name="arguments">-c 3 Generics/parReg/pdx/Pdx/csPartitionRegion.xml</data>
      <client-set name="JCS1"/>
    </task>
    <task name="StartCacheServers" action="doRunProcess" container="utils" waitTime="5m" parallel="true">
      <data name="program">startJavaServers</data>
      <data name="arguments">1</data>
      <client-set name="JCS1"/>
    </task>
    <task name="StartCacheServers" action="doRunProcess" container="utils" waitTime="5m" parallel="true">
      <data name="program">startJavaServers</data>
      <data name="arguments">2</data>
      <client-set name="JCS2"/>
    </task>
    <task name="StartCacheServers" action="doRunProcess" container="utils" waitTime="5m" parallel="true">
      <data name="program">startJavaServers</data>
      <data name="arguments">3</data>
      <client-set name="JCS3"/>
    </task>
    <task name="CreatePool" action="doCreatePool" container="NewFwkLib.GemStone.GemFire.Cache.FwkLib.pdxtests" argTypes="String,Object"  waitTime="3m">
      <data name="poolSpec">ThinClientPool1</data>
      <client-set count="4" name="Client"/>
    </task>
    <task name="CreateRegion" action="doCreateRegion" container="NewFwkLib.GemStone.GemFire.Cache.FwkLib.pdxtests" argTypes="String,Object"  waitTime="5m">
      <client-set begin="1" count="2" name="Client"/>
      <data name="regionSpec">ThinClientRegion</data>
	  <data name="versionNum">1</data>
    </task>
    <task name="CreateRegion" action="doCreateRegion" container="NewFwkLib.GemStone.GemFire.Cache.FwkLib.pdxtests" argTypes="String,Object"  waitTime="5m">
      <client-set begin="3" count="2" name="Client"/>
      <data name="regionSpec">EmptyClientRegion</data>
 	 <!--data name="objectType">PdxVersioned</data-->
	  <data name="versionNum">2</data>
    </task>
    <task name="Create Object" action="doPopulateRegion" container="NewFwkLib.GemStone.GemFire.Cache.FwkLib.pdxtests" waitTime="30m" argTypes="String,Object">
      <data name="entryOps">
        <oneof>
          <item>create</item>
         </oneof>
      </data>
      <data name="versionNum">2</data>
      <client-set begin="3" count="2" name="Client"/>
    </task>
    <task name="Do put" action="doPuts" container="NewFwkLib.GemStone.GemFire.Cache.FwkLib.pdxtests" waitTime="30m" argTypes="String,Object">
      <data name="entryOps">
        <oneof>
          <item>update</item>
         </oneof>
      </data>
      <data name="versionNum">2</data>
      <client-set begin="3" count="2" name="Client"/>
    </task>
    <task name="Do get" action="doGets" container="NewFwkLib.GemStone.GemFire.Cache.FwkLib.pdxtests" waitTime="30m" argTypes="String,Object">
      <data name="entryOps">
        <oneof>
          <item>get</item>
         </oneof>
      </data>
      <client-set begin="1" count="2" name="Client"/>
    </task>
    <task name="ValidateFromSnapshot" action="verifyFromSnapshot" container="NewFwkLib.GemStone.GemFire.Cache.FwkLib.pdxtests" waitTime="30m" argTypes="String,Object">
      <client-set begin="1" count="2" name="Client"/>
    </task>
    <task name="Do Put" action="doPuts" container="NewFwkLib.GemStone.GemFire.Cache.FwkLib.pdxtests" waitTime="30m" argTypes="String,Object">
      <data name="entryOps">
        <oneof>
          <item>update</item>
         </oneof>
      </data>
      <data name="versionNum">1</data>
      <client-set begin="1" count="2" name="Client"/>
    </task>
    <task name="Do Get" action="doGets" container="NewFwkLib.GemStone.GemFire.Cache.FwkLib.pdxtests" waitTime="30m" argTypes="String,Object">
      <data name="entryOps">
        <oneof>
          <item>get</item>
         </oneof>
      </data>
      <client-set begin="3" count="2" name="Client"/>
    </task>
    <task name="ValidateFromSnapshot" action="verifyFromSnapshot" container="NewFwkLib.GemStone.GemFire.Cache.FwkLib.pdxtests" waitTime="30m" argTypes="String,Object">
      <client-set begin="3" count="2" name="Client"/>
    </task>
    <task name="Do Get" action="doGets" container="NewFwkLib.GemStone.GemFire.Cache.FwkLib.pdxtests" waitTime="30m" argTypes="String,Object">
      <data name="entryOps">
        <oneof>
          <item>get</item>
         </oneof>
      </data>
      <client-set begin="1" count="2" name="Client"/>
    </task>
    <task name="ValidateFromSnapshot" action="verifyFromSnapshot" container="NewFwkLib.GemStone.GemFire.Cache.FwkLib.pdxtests" waitTime="30m" argTypes="String,Object">
      <client-set begin="1" count="2" name="Client"/>
    </task>
    <task name="Close Cache" action="doCloseCache" container="NewFwkLib.GemStone.GemFire.Cache.FwkLib.smokeperf" argTypes="String,Object"  waitTime="5m"/>
    <task name="StopCacheServers" action="doRunProcess" container="utils" waitTime="5m" parallel="true">
      <data name="program">stopJavaServers</data>
      <data name="arguments">1</data>
      <client-set name="JCS1"/>
    </task>
    <task name="StopCacheServers" action="doRunProcess" container="utils" waitTime="5m" parallel="true">
      <data name="program">stopJavaServers</data>
      <data name="arguments">2</data>
      <client-set name="JCS2"/>
    </task>
    <task name="StopCacheServers" action="doRunProcess" container="utils" waitTime="5m" parallel="true">
      <data name="program">stopJavaServers</data>
      <data name="arguments">3</data>
      <client-set name="JCS3"/>
    </task>

  </test>

</test-driver>
