=== apache/geode/geode-client-native/src/tests/xml/testDefinition.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:include schemaLocation="gfcpp-cache.xsd" />
  <xs:element name="test-driver" type="Test-Driver">
    <xs:annotation>
      <xs:documentation>The container for all the information required to perform a test. This is
        the root level element.</xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:complexType name="Test-Driver">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="localFile" type="Local-File" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="data" type="Data" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="data-set" type="Data-Set" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="client-set" type="Client-Set" minOccurs="0" />
      <xs:element name="test" type="Test" minOccurs="0" maxOccurs="unbounded" />
    </xs:choice>
    <xs:attribute name="version" type="xs:string" use="optional" />
  </xs:complexType>
  <xs:complexType name="Test">
    <xs:annotation>
      <xs:documentation>A collection of tasks that comprise a single test.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="task" type="Task" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Printed in some log messages.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="description" type="xs:string" use="optional">
      <xs:annotation>
        <xs:documentation>Not logged currently.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="waitTime" type="xs:string" use="optional">
      <xs:annotation>
        <xs:documentation>Not recommended for use, will cause test to fail if it has not completed
          in this number of seconds.</xs:documentation>
        <xs:documentation>Use the waitTime associated with tasks instead.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="timesToRun" type="xs:int" use="optional">
      <xs:annotation>
        <xs:documentation>Total number of times to run this task. If any executions of the task
          return an error status, further execution of the task will continue, only if
          continueOnError is set to true.</xs:documentation>
        <xs:documentation>timesToRun defaults to once per client, specifying "1" would run it once
          on one client.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  <xs:complexType name="Task">
    <xs:annotation>
      <xs:documentation>A single task, currently a function within a library, for
      execution.</xs:documentation>
    </xs:annotation>
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="data" type="Data" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="client-set" type="Client-Set" minOccurs="0" />
    </xs:choice>
    <xs:attribute name="name" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Name of the task, used in some log messages.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="action" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>The name of the extern "C" function that will be looked up in the library
          and executed.</xs:documentation>
        <xs:documentation>The reason for calling it an action is to not marry too tightly the notion
          that this is only a function, in the future it should be possible to extend support to
          different flavors of clients.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="class" type="xs:string" use="optional">
      <xs:annotation>
        <xs:documentation>The name of the class to load, when using assemblies.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="container" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>The name of the library to load.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="waitTime" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>The number of seconds to wait for task to complete before assuming client
          is hung and killing it.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="timesToRun" type="xs:int" use="optional">
      <xs:annotation>
        <xs:documentation>Total number of times to run this task. If any executions of the task
          return an error status, further execution of the task will continue, only if
          continueOnError is set to true.</xs:documentation>
        <xs:documentation>timesToRun defaults to once per client, specifying "1" would run it once
          on one client.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="threadCount" type="xs:int" use="optional">
      <xs:annotation>
        <xs:documentation>Number of threads each client should run this task on.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="parallel" type="xs:boolean" use="optional">
      <xs:annotation>
        <xs:documentation>Run this task in parallel with the previous task.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="continueOnError" type="xs:boolean" use="optional">
      <xs:annotation>
        <xs:documentation>When running this task multiple times, continue to schedule it on clients,
          even if any results returned have been failures.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  <xs:complexType name="Local-File">
    <xs:annotation>
      <xs:documentation>Specify content for a file, may optionally specify whether to append to
        existing file, default is to append.</xs:documentation>
    </xs:annotation>
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="append" type="xs:boolean" use="optional" default="false" />
        <xs:attribute name="description" type="xs:string" use="optional" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="Client-Set">
    <xs:annotation>
      <xs:documentation>A collection of client elements.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="client" type="Client" maxOccurs="unbounded" minOccurs="0" />
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="optional" />
    <xs:attribute name="exclude" type="xs:boolean" use="optional" />
    <xs:attribute name="count" type="xs:int" use="optional" />
    <xs:attribute name="begin" type="xs:int" use="optional" />
    <xs:attribute name="hostGroup" type="xs:string" use="optional" />
    <xs:attribute name="remaining" type="xs:boolean" use="optional" />
  </xs:complexType>
  <xs:complexType name="Client">
    <xs:annotation>
      <xs:documentation>A single client, used when it is necessary to restrain what clients will be
        used for a particular task.</xs:documentation>
      <xs:documentation>Also useful for specifying a minimum number of clients for the test,
        regardless of how few hosts are provided on the commandline.</xs:documentation>
    </xs:annotation>
    <xs:attribute name="name" type="xs:string" use="required" />
    <xs:attribute name="program" type="xs:string" use="optional" />
    <xs:attribute name="arguments" type="xs:string" use="optional" />
  </xs:complexType>
  <xs:complexType name="Data-Set">
    <xs:annotation>
      <xs:documentation>A collection of data elements.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="data" type="Data" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="optional" />
  </xs:complexType>
  <xs:complexType name="Data" mixed="true">
    <xs:annotation>
      <xs:documentation>Data item that can be accessed by name from the application at
      runtime.</xs:documentation>
    </xs:annotation>
    <xs:choice minOccurs="0" maxOccurs="1">
      <xs:element name="list" type="List" />
      <xs:element name="oneof" type="Oneof" />
      <xs:element name="range" type="Range" />
      <xs:element name="snippet" type="Snippet" />
    </xs:choice>
    <xs:attribute name="name" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>The name to be used in the application to find the value associated with
          this data element.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  <xs:complexType name="List">
    <xs:annotation>
      <xs:documentation>A list of items that can be accessed from the application using first, next
        semantics.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="item" type="xs:string" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="Oneof">
    <xs:annotation>
      <xs:documentation>A data item that randomly returns one of the items it contains each time
        getValue is called on it.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="item" type="xs:string" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="Range">
    <xs:annotation>
      <xs:documentation>A random number between its low and high attribute values will be returned
        each time its getValue function is called.</xs:documentation>
    </xs:annotation>
    <xs:attribute name="low" type="xs:double" use="required">
      <xs:annotation>
        <xs:documentation>Low end of range used in selecting a random number.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="high" type="xs:double" use="required">
      <xs:annotation>
        <xs:documentation>High end of range used in selecting a random number.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  <xs:complexType name="Snippet">
    <xs:annotation>
      <xs:documentation>A root-region element as would be suitable for a cache.xml
      file.</xs:documentation>
    </xs:annotation>
    <xs:choice>
      <xs:element name="region" type="Region" />
      <xs:element name="pool" type="Pool" />
    </xs:choice>
  </xs:complexType>
</xs:schema>

=== apache/geode/geode-client-native/src/tests/xml/Generics/parReg/tx/concDeltaReplicateBridge.xml
<?xml version="1.0" encoding="UTF-8"?>
<test-driver version="1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../testDefinition.xsd">

  <data name="timedInterval">10m</data>
  <data name="cacheType">CLIENT</data>

  <data name="distinctKeys">
    <list>
      <item>100</item>
    </list>
  </data>

  <data name="valueSizes">
    <list>
      <item>10</item>
    </list>
  </data>
  <data name="numThreads">
    <list>
      <item>10</item>
    </list>
  </data>
<data name="useTransactions">true</data>
  <data name="keyType">str</data>
  
 <data name="ThinClientPool">
   <snippet>
     <pool name="_Test_Pool1" pr-single-hop-enabled="false" subscription-enabled="true" locators="true" ping-interval="100" read-timeout="60000" subscription-redundancy="3" />
   </snippet>
 </data>
  
  <data name="ThinClientRegion">
    <snippet>
      <region name="TestTCR1">
        <region-attributes caching-enabled="true" pool-name="_Test_Pool1" client-notification="true">
        </region-attributes>  
      </region>
    </snippet>
  </data>
  <data name="ThinClientRegionWithListener">
    <snippet>
      <region name="TestTCR1">
        <region-attributes caching-enabled="true" pool-name="_Test_Pool1" client-notification="true">
        <cache-listener library="deltatest" function="createDeltaValidationCacheListener"/>
        <cache-listener library="cacheserver" function="createSilenceListener"/>
        </region-attributes>  
      </region>
    </snippet>
  </data>
 
  <client-set name="JCS1" hostGroup="CS"/>
  <client-set name="JCS2" hostGroup="CS"/>
  <client-set name="JCS3" hostGroup="CS"/>
  <client-set name="JCS4" hostGroup="CS"/>
  <client-set count="4" name="Client"/>
  <client-set name="Feeder"/>

  <test name="deltaPropogationNoConflationTest" description="Test delta propagation in a concurrent test with validation in a bridge configuration with replicate region">
    <task name="SetupCacheServer CS1" action="doRunProcess" container="utils" waitTime="5m">
      <data name="program">setupJavaServers</data>
      <data name="arguments">-e CLASSPATH=\$BUILDDIR/framework/lib/javaobject.jar:\$CLASSPATH -c 4 Delta/csDeltaNoConflate.xml</data>
      <client-set name="JCS1"/>
    </task>
    <task name="StartCacheServers1" action="doRunProcess" container="utils" waitTime="5m">
      <data name="program">startJavaServers</data>
      <data name="arguments">1</data>
      <client-set name="JCS1"/>
    </task>
    <task name="StartCacheServers2" action="doRunProcess" container="utils" waitTime="5m">
      <data name="program">startJavaServers</data>
      <data name="arguments">2</data>
      <client-set name="JCS2"/>
    </task>
    <task name="StartCacheServers3" action="doRunProcess" container="utils" waitTime="5m">
      <data name="program">startJavaServers</data>
      <data name="arguments">3</data>
      <client-set name="JCS3"/>
    </task>
    <task name="StartCacheServers4" action="doRunProcess" container="utils" waitTime="5m">
      <data name="program">startJavaServers</data>
      <data name="arguments">4</data>
      <client-set name="JCS4"/>
    </task>
    <task name="CreatePool" action="doCreatePool" container="NewFwkLib.GemStone.GemFire.Cache.FwkLib.deltatest" waitTime="5m" argTypes="String,DeltaTestImpl">
      <data name="poolSpec">ThinClientPool</data>
      <client-set  count="4"  name="Client"/>
      <client-set name="Feeder"/>
    </task>
     <task name="CreateRegion" action="doCreateRegion" container="NewFwkLib.GemStone.GemFire.Cache.FwkLib.deltatest" waitTime="5m" argTypes="String,DeltaTestImpl">
      <client-set count="4" name="Client"/>
      <data name="regionSpec">ThinClientRegionWithListener</data>
    </task>
    <task name="CreateRegion" action="doCreateRegion" container="NewFwkLib.GemStone.GemFire.Cache.FwkLib.deltatest" waitTime="5m" argTypes="String,DeltaTestImpl">
      <client-set name="Feeder"/>
      <data name="regionSpec">ThinClientRegion</data>
    </task>
    <task name="Register All Keys" action="doRegisterAllKeys" container="NewFwkLib.GemStone.GemFire.Cache.FwkLib.deltatest" waitTime="2m" argTypes="String,DeltaTestImpl">
      <data name="regionName">TestTCR1</data>
      <client-set count="4" name="Client"/>
    </task>
    <task name="Populating Entries in Region" action="doPopulateRegion" container="NewFwkLib.GemStone.GemFire.Cache.FwkLib.deltatest" waitTime="10m" argTypes="String,DeltaTestImpl">
      <data name="regionName">TestTCR1</data>
      <data name="opsSecond">5</data>
      <client-set name="Feeder"/>
    </task>
    <task name="do random entry ops " action="doEntryOperation" container="NewFwkLib.GemStone.GemFire.Cache.FwkLib.deltatest" waitTime="30m" parallel="true" argTypes="String,DeltaTestImpl">
      <data name="entryOps">
        <oneof>
          <item>put</item>
          <item>put</item>
          <!--item>destroy</item-->
          <item>put</item>
        </oneof>
      </data>
      <data name="regionName">TestTCR1</data>
      <data name="opsSecond">5</data>
      <client-set name="Feeder"/>
    </task>
    <task name="doSleep" action="doSleep" container="utils" waitTime="160">
      <client-set count="4" name="Client"/>
      <data name="sleepTime">60</data>
    </task>
    <task name="validate test" action="doValidateDeltaTest" container="NewFwkLib.GemStone.GemFire.Cache.FwkLib.deltatest" waitTime="5m" argTypes="String,DeltaTestImpl">
      <client-set count="4" name="Client"/>
    </task>
    <task name="Close Cache" action="doCloseCache" container="NewFwkLib.GemStone.GemFire.Cache.FwkLib.deltatest" waitTime="5m" argTypes="String,DeltaTestImpl"/>
    <task name="StopCacheServers1" action="doRunProcess" container="utils" waitTime="5m" parallel="true">
      <data name="program">stopJavaServers</data>
      <data name="arguments">1</data>
      <client-set name="JCS1"/>
    </task>
    <task name="StopCacheServers2" action="doRunProcess" container="utils" waitTime="5m" parallel="true">
      <data name="program">stopJavaServers</data>
      <data name="arguments">2</data>
      <client-set name="JCS2"/>
    </task>
    <task name="StopCacheServers3" action="doRunProcess" container="utils" waitTime="5m" parallel="true">
      <data name="program">stopJavaServers</data>
      <data name="arguments">3</data>
      <client-set name="JCS3"/>
    </task>
    <task name="StopCacheServers4" action="doRunProcess" container="utils" waitTime="5m" parallel="true">
      <data name="program">stopJavaServers</data>
      <data name="arguments">4</data>
      <client-set name="JCS4"/>
    </task>
 </test>

</test-driver>

=== apache/geode/geode-client-native/src/tests/xml/Native/CyberTraderInterestListUpdateTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<test-driver version="1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../testDefinition.xsd">

  <data name="timedInterval">100</data>
  <data name="cacheType">CLIENT</data>

  <data name="distinctKeys">
    <list>
      <item>1848</item>
    </list>
  </data>
  <data name="expectedCount">1848</data>

  <data name="valueSizes">
    <list>
      <item>3000</item>
    </list>
  </data>
  <data name="numThreads">
    <list>
      <item>1</item>
    </list>
  </data>

  <data name="keyType">str</data>

  <data name="ThinClientRegion">
    <snippet>
      <region name="TestTCR1">
        <region-attributes caching-enabled="true"
            initial-capacity="18500" client-notification="true"/>
      </region>
    </snippet>
  </data>
  <data name="regionSpec">ThinClientRegion</data>

  <client-set name="JCS1" hostGroup="CS"/>
  <client-set name="JCS2" hostGroup="CS"/>
  <client-set name="Publisher"/>
  <client-set name="Subscriber"/>

  <test name="ThinClientPerf" description="Thin Client perf test">
    <task name="SetupCacheServer CS1" action="doRunProcess" container="utils" waitTime="5m">
      <data name="program">setupJavaServers</data>
      <data name="arguments">-c 2 Native/csNotifySubscription.xml</data>
      <client-set name="JCS1"/>
    </task>
    <task name="StartCacheServers" action="doRunProcess" container="utils" waitTime="5m" parallel="true">
      <data name="program">startJavaServers</data>
      <data name="arguments">1</data>
      <client-set name="JCS1"/>
    </task>
    <task name="StartCacheServers" action="doRunProcess" container="utils" waitTime="5m" parallel="true">
      <data name="program">startJavaServers</data>
      <data name="arguments">2</data>
      <client-set name="JCS2"/>
    </task>
    <task name="CreateRegion" action="doCreateRegion" container="perftests" waitTime="5m">
      <client-set name="Publisher"/>
      <client-set name="Subscriber"/>
    </task>
    <task name="Populate Entries in publisher" action="doPuts" container="perftests" waitTime="15m">
      <client-set name="Publisher"/>
    </task>
    <task name="Register Interest List" action="doRegisterInterestList" container="perftests" waitTime="15m">
      <data name="registerKeys">1000</data>
      <data name="keyIndexBegin">100</data>
      <client-set name="Subscriber"/>
    </task>
    <task name="Gets Entries in Subscriber" action="doGets" container="perftests" waitTime="15m">
      <client-set name="Subscriber"/>
    </task>
    <task name="Update Entries from Publisher" action="doPuts" container="perftests" waitTime="15m">
      <data name="valueSizes">
        <list>
          <item>500</item>
        </list>
      </data>
      <client-set name="Publisher"/>
    </task>
    <task name="doSleep" action="doSleep" container="utils" waitTime="60">
      <client-set name="Subscriber"/>
      <data name="sleepTime">5</data>
    </task>
    <task name="Verify update list" action="doVerifyInterestList" container="perftests" waitTime="15m">
      <client-set name="Subscriber"/>
      <data name="registerKeys">1000</data>
      <data name="keyIndexBegin">100</data>
      <data name="valueSizes">500</data>
    </task>
    <task name="Close Cache" action="doCloseCache" container="perftests" waitTime="2m"/>
    <task name="StopCacheServers" action="doRunProcess" container="utils" waitTime="5m" parallel="true">
      <data name="program">stopJavaServers</data>
      <data name="arguments">1</data>
      <client-set name="JCS1"/>
    </task>
    <task name="StopCacheServers" action="doRunProcess" container="utils" waitTime="5m" parallel="true">
      <data name="program">stopJavaServers</data>
      <data name="arguments">2</data>
      <client-set name="JCS2"/>
    </task>
  </test>

</test-driver>

=== apache/geode/geode-client-native/src/tests/xml/Security/NativePR/clientAuthnAndAuthzFailoverPrMU.xml
<?xml version="1.0" encoding="UTF-8"?>
<test-driver version="1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../testDefinition.xsd">
  <data name="BBName">CacheServer</data>
  <data name="cacheType">CLIENT</data>
  <data name="securityScheme">
   <list>
      <item>DUMMY</item>
      <item>LDAP</item>
      <item>PKCS</item>
   </list>
  </data>

 <data name="redundancyLevel">1</data>
  <data name="minServers">2</data>
  <data name="isFailover">true</data>
  
  <data name="sleepTime">
    <oneof>
      <item>20</item>
      <item>30</item>
      <item>40</item>
      <item>50</item>
      <item>60</item>
      <item>90</item>
      <item>120</item>
    </oneof>
  </data>
  <data name="operation">
    <oneof>
      <item>stop</item>
      <item>term</item>
      <item>kill</item>
    </oneof>
  </data>
 
  <data name="ThinClientRegion">
    <snippet>
      <region name="Portfolios">
        <region-attributes scope="distributed-ack" caching-enabled="false" client-notification="false"/>
      </region>
    </snippet>
  </data>

  <client-set name="JCS1" hostGroup="CS"/>
  <client-set name="JCS2" hostGroup="CS"/>
  <client-set name="JCS3" hostGroup="CS"/>
  <client-set count="2" name="Client"/>
  
  <test name="MultiUser Security tests" description="To verify multiple users Authentication and Authorization in Failover case" timesToRun="3">
    <task name="SetupCacheServer" action="doRunProcess" container="utils" waitTime="5m">
      <data name="program">setupJavaServers</data>
      <data name="arguments">-e CLASSPATH=\$BUILDDIR/framework/lib/javaobject.jar:\$CLASSPATH -c 3 Security/NativePR/csNotifySubscriptionSecurity.xml</data>
      <client-set name="JCS1"/>
    </task>
    <task name="StartCacheServer 1" action="doRunProcess" container="utils" waitTime="10m" >
      <data name="program">startJavaServers</data>
      <data name="arguments">1</data>
      <data name="securityParams">:authenticator:authorizer</data>
      <data name ="multiUserMode">true</data>
      <client-set name="JCS1"/>
    </task>
    <task name="StartCacheServer 2" action="doRunProcess" container="utils" waitTime="10m" parallel="true">
      <data name="program">startJavaServers</data>
      <data name="arguments">2</data>
      <data name="securityParams">:authenticator:authorizer</data>
      <data name ="multiUserMode">true</data>
      <client-set name="JCS2"/>
    </task>
    <task name="StartCacheServer 3" action="doRunProcess" container="utils" waitTime="10m" parallel="true">
      <data name="program">startJavaServers</data>
      <data name="arguments">3</data>
      <data name="securityParams">:authenticator:authorizer</data>
      <data name ="multiUserMode">true</data>
      <client-set name="JCS3"/>
    </task>
    <task name="CreateClient" action="doCreateRegion" container="multiusersecurity" waitTime="10m">
      <data name="regionSpec">ThinClientRegion</data>
      <data name ="multiUserMode">true</data> 
      <data name="MultiUsers">9</data>
      <data name="LDAP">
        <oneof>
         <item>gemfire</item>  
        </oneof>    
      </data>
      <data name="PKCS">
        <oneof>
         <item>gemfire</item>  
        </oneof>    
      </data>
      <data name="DUMMY">
        <oneof>
         <item>user</item>  
        </oneof>    
      </data>
      <client-set count="2" name="Client"/>
    </task>
    <task name="FeedSystem" action="doFeedTask" container="multiusersecurity" waitTime="40m">
      <data name="entryCount">10000</data>
      <client-set count="1" name="Client"/>
    </task>
    <task name="Client Events" action="doEntryOperationsForMU" container="multiusersecurity" waitTime="30m" parallel="true">
      <data name="entryOps">
        <oneof>
          <item>create</item>
          <item>update</item>
          <item>update</item>
          <item>get</item>
          <item>get</item>
          <item>getServerKeys</item>
          <item>getServerKeys</item>
          <item>destroy</item>
          <item>destroy</item>
          <item>putAll</item>
          <item>putAll</item>
          <item>query</item>
          <item>query</item>
          <item>cq</item>
          <item>cq</item>
          <item>executefunction</item>
          <item>executefunction</item>
        </oneof>
      </data>
      <data name="workTime">15m</data>
      <data name="opsSecond">12</data>
      <data name="entryCount">10000</data>
      <client-set count="2" name="Client"/>
    </task>
    <task name="stopStartCacheServer 1" action="doStopStartServer" container="utils" timesToRun="2" waitTime="30m" continueOnError="true" parallel="true">
      <data name="ServerId">1</data>
      <data name="securityParams">:authenticator:authorizer</data>
      <data name ="multiUserMode">true</data>
      <client-set name="JCS1"/>
    </task>
    <task name="stopStartCacheServer 2" action="doStopStartServer" container="utils" timesToRun="2" waitTime="30m" continueOnError="true" parallel="true">
      <data name="ServerId">2</data>
      <data name="securityParams">:authenticator:authorizer</data>
      <data name ="multiUserMode">true</data>
      <client-set name="JCS2"/>
    </task>
    <task name="stopStartCacheServer 3" action="doStopStartServer" container="utils" timesToRun="2" waitTime="30m" continueOnError="true" parallel="true">
      <data name="ServerId">3</data>
      <data name="securityParams">:authenticator:authorizer</data>
      <data name ="multiUserMode">true</data>
      <client-set name="JCS3"/>
    </task>
    <task name=" Validate for per user" action="doValidateEntryOperationsForPerUser" container="multiusersecurity" waitTime="5m">
       <client-set count="2" name="Client"/>
    </task>
    <task name="Close Cache" action="doCloseCache" container="multiusersecurity" waitTime="2m"/>
    <task name="StopCacheServer 1" action="doRunProcess" container="utils" waitTime="10m" parallel="true">
      <data name="program">stopJavaServers</data>
      <data name="arguments">1</data>
      <client-set name="JCS1"/>
    </task>
    <task name="StopCacheServer 2" action="doRunProcess" container="utils" waitTime="10m" parallel="true">
      <data name="program">stopJavaServers</data>
      <data name="arguments">2</data>
      <client-set name="JCS2"/>
    </task>
    <task name="StopCacheServer 3" action="doRunProcess" container="utils" waitTime="10m" parallel="true">
      <data name="program">stopJavaServers</data>
      <data name="arguments">3</data>
      <client-set name="JCS3"/>
    </task>
  </test>
</test-driver>
